# Custom build of Iosevka font.
# https://github.com/be5invis/Iosevka
#
# Three variants:
#   Mono (for coding)
#   Fixed (for terminal)
#   Prop (quasi-proportional, for comment and docs)
#
# Properties:
#   Type: Serif-slab
#   4 styles: regular, italic, bold, bold-italic
#   width: normal as extended
#   No ligations
#
# How to make a custom build:
#   1. Create a custom build configuration using https://typeof.net/Iosevka/customizer
#   2. Save your configuration as private-build-plans.toml (Add more as needed)
#   3. Go to the directory where private-build-plans.toml is located
#   4. Run `docker run -it -v $(pwd):/build avivace/iosevka-build -- ttf::adm-hybrid-mono ttf::adm-hybrid-fixed ttf::adm-hybrid-prop`
#
# Build from source repo
#   1. Create a custom build configuration using https://typeof.net/Iosevka/customizer
#   2. Save your configuration as private-build-plans.toml (Add more as needed)
#   3. Put private-build-plans.toml under the root directory of the repo
#   4. Install nodejs and ttfautohint
#   5. Go to the root directory of the repo
#   6. Run `npm install; npm run build -- ttf::adm-hybrid-mono ttf::adm-hybrid-fixed ttf::adm-hybrid-prop;`
#
# Ref: https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md

# mono
[buildPlans.adm-hybrid-mono]
family = "Adm Hybrid Mono"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
no-ligation = true

[buildPlans.adm-hybrid-mono.variants.design]
capital-a = "straight-top-serifed"
capital-b = "more-asymmetric-unilateral-serifed"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "top-left-serifed"
capital-j = "flat-hook-serifed"
capital-k = "symmetric-touching-top-left-serifed"
capital-l = "motion-serifed"
capital-m = "slanted-sides-hanging-motion-serifed"
capital-n = "motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "straight"
capital-r = "straight-motion-serifed"
capital-t = "motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-flat-top-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "straight-top-serifed"
b = "toothless-corner-motion-serifed"
d = "toothed-top-serifed"
f = "flat-hook-crossbar-at-x-height"
g = "double-storey-open"
h = "straight-top-left-serifed"
i = "hooky"
j = "flat-hook-serifed"
k = "symmetric-touching-top-left-serifed"
l = "zshaped"
m = "top-left-serifed"
n = "straight-top-left-serifed"
p = "motion-serifed"
r = "corner-hooked-top-serifed"
t = "flat-hook-short-neck2"
v = "straight-motion-serifed"
w = "straight-flat-top-motion-serifed"
x = "straight-motion-serifed"
y = "straight-turn-motion-serifed"
z = "straight-top-serifed"
zero = "slashed-split-oval"
one = "base-flat-top-serif"
two = "straight-neck"
three = "flat-top"
five = "oblique-upper-left-bar"
eight = "two-circles"
asterisk = "turn-hex-low"
number-sign = "slanted"
ampersand = "upper-open"
at = "fourfold-solid-inner"
percent = "dots"
question = "corner"
punctuation-dot = "square"

[buildPlans.adm-hybrid-mono.variants.italic]
capital-h = "top-left-bottom-right-serifed"
capital-k = "symmetric-touching-top-left-and-bottom-right-serifed"
a = "single-storey-serifed"
d = "toothed-serifed"
e = "flat-crossbar"
f = "flat-hook-extended-crossbar-at-x-height"
g = "single-storey-flat-hook-serifless"
h = "straight-motion-serifed"
i = "zshaped"
j = "flat-hook-serifed"
k = "symmetric-touching-top-left-and-bottom-right-serifed"
m = "top-left-and-bottom-right-serifed"
n = "straight-motion-serifed"
u = "bottom-right-serifed"

[buildPlans.adm-hybrid-mono.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.adm-hybrid-mono.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.adm-hybrid-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.adm-hybrid-mono.slopes.italic]
angle = 12
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.adm-hybrid-mono.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.adm-hybrid-mono.metric-override]
cap = 696
xHeight = 515
parenSize = 926
symbolMid=322
leading=1228
archDepth=245
smallArchDepth=250

# Fixed
[buildPlans.adm-hybrid-fixed]
family = "Adm Hybrid Fixed"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true
no-ligation = true

[buildPlans.adm-hybrid-fixed.variants.design]
capital-a = "straight-top-serifed"
capital-b = "more-asymmetric-unilateral-serifed"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "top-left-serifed"
capital-j = "flat-hook-serifed"
capital-k = "symmetric-touching-top-left-serifed"
capital-l = "motion-serifed"
capital-m = "slanted-sides-hanging-motion-serifed"
capital-n = "motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "straight"
capital-r = "straight-motion-serifed"
capital-t = "motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-flat-top-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "straight-top-serifed"
b = "toothless-corner-motion-serifed"
d = "toothed-top-serifed"
f = "flat-hook-crossbar-at-x-height"
g = "double-storey-open"
h = "straight-top-left-serifed"
i = "hooky"
j = "flat-hook-serifed"
k = "symmetric-touching-top-left-serifed"
l = "zshaped"
m = "top-left-serifed"
n = "straight-top-left-serifed"
p = "motion-serifed"
r = "corner-hooked-top-serifed"
t = "flat-hook-short-neck2"
v = "straight-motion-serifed"
w = "straight-flat-top-motion-serifed"
x = "straight-motion-serifed"
y = "straight-turn-motion-serifed"
z = "straight-top-serifed"
zero = "slashed-split-oval"
one = "base-flat-top-serif"
two = "straight-neck"
three = "flat-top"
five = "oblique-upper-left-bar"
eight = "two-circles"
asterisk = "turn-hex-low"
number-sign = "slanted"
ampersand = "upper-open"
at = "fourfold-solid-inner"
percent = "dots"
question = "corner"
punctuation-dot = "square"

[buildPlans.adm-hybrid-fixed.variants.italic]
capital-h = "top-left-bottom-right-serifed"
capital-k = "symmetric-touching-top-left-and-bottom-right-serifed"
a = "single-storey-serifed"
d = "toothed-serifed"
e = "flat-crossbar"
f = "flat-hook-extended-crossbar-at-x-height"
g = "single-storey-flat-hook-serifless"
h = "straight-motion-serifed"
i = "zshaped"
j = "flat-hook-serifed"
k = "symmetric-touching-top-left-and-bottom-right-serifed"
m = "top-left-and-bottom-right-serifed"
n = "straight-motion-serifed"
u = "bottom-right-serifed"

[buildPlans.adm-hybrid-fixed.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.adm-hybrid-fixed.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.adm-hybrid-fixed.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.adm-hybrid-fixed.slopes.italic]
angle = 12
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.adm-hybrid-fixed.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.adm-hybrid-fixed.metric-override]
cap = 696
xHeight = 515
parenSize = 926
symbolMid=322
leading=1228
archDepth=245
smallArchDepth=250

# quasi-proportional
[buildPlans.adm-hybrid-prop]
family = "Adm Hybrid Prop"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true
no-ligation = true

[buildPlans.adm-hybrid-prop.variants.design]
capital-a = "straight-top-serifed"
capital-b = "more-asymmetric-unilateral-serifed"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "top-left-serifed"
capital-j = "flat-hook-serifed"
capital-k = "symmetric-touching-top-left-serifed"
capital-l = "motion-serifed"
capital-m = "slanted-sides-hanging-motion-serifed"
capital-n = "motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "straight"
capital-r = "straight-motion-serifed"
capital-t = "motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-flat-top-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "straight-top-serifed"
b = "toothless-corner-motion-serifed"
d = "toothed-top-serifed"
f = "flat-hook-crossbar-at-x-height"
g = "double-storey-open"
h = "straight-top-left-serifed"
i = "hooky"
j = "flat-hook-serifed"
k = "symmetric-touching-top-left-serifed"
l = "zshaped"
m = "top-left-serifed"
n = "straight-top-left-serifed"
p = "motion-serifed"
r = "corner-hooked-top-serifed"
t = "flat-hook-short-neck2"
v = "straight-motion-serifed"
w = "straight-flat-top-motion-serifed"
x = "straight-motion-serifed"
y = "straight-turn-motion-serifed"
z = "straight-top-serifed"
zero = "slashed-split-oval"
one = "base-flat-top-serif"
two = "straight-neck"
three = "flat-top"
five = "oblique-upper-left-bar"
eight = "two-circles"
asterisk = "turn-hex-low"
number-sign = "slanted"
ampersand = "upper-open"
at = "fourfold-solid-inner"
percent = "dots"
question = "corner"
punctuation-dot = "square"

[buildPlans.adm-hybrid-prop.variants.italic]
capital-h = "top-left-bottom-right-serifed"
capital-k = "symmetric-touching-top-left-and-bottom-right-serifed"
a = "single-storey-serifed"
d = "toothed-serifed"
e = "flat-crossbar"
f = "flat-hook-extended-crossbar-at-x-height"
g = "single-storey-flat-hook-serifless"
h = "straight-motion-serifed"
i = "zshaped"
j = "flat-hook-serifed"
k = "symmetric-touching-top-left-and-bottom-right-serifed"
m = "top-left-and-bottom-right-serifed"
n = "straight-motion-serifed"
u = "bottom-right-serifed"

[buildPlans.adm-hybrid-prop.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.adm-hybrid-prop.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.adm-hybrid-prop.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.adm-hybrid-prop.slopes.italic]
angle = 12
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.adm-hybrid-prop.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.adm-hybrid-prop.metric-override]
cap = 696
xHeight = 515
parenSize = 926
symbolMid=322
leading=1228
archDepth=245
smallArchDepth=250
