# Custom build of Iosevka font.
# https://github.com/be5invis/Iosevka
#
# Three variants:
#   Mono (for coding)
#   Fixed (for terminal)
#   Prop (quasi-proportional, for comment and docs)
#
# Properties:
#   Type: Serif-slab
#   4 styles: regular, italic, bold, bold-italic
#   width: normal as extended
#   No ligations
#
# How to make a custom build:
#   1. Create a custom build configuration using https://typeof.net/Iosevka/customizer
#   2. Save your configuration as private-build-plans.toml (Add more as needed)
#   3. Go to the directory where private-build-plans.toml is located
#   4. Run `docker run -it -v $(pwd):/build avivace/iosevka-build -- ttf::adm-mono ttf::adm-fixed ttf::adm-prop`
#
# Build from source repo
#   1. Create a custom build configuration using https://typeof.net/Iosevka/customizer
#   2. Save your configuration as private-build-plans.toml (Add more as needed)
#   3. Put private-build-plans.toml under the root directory of the repo
#   4. Install nodejs and ttfautohint
#   5. Go to the root directory of the repo
#   6. Run `npm install; npm run build -- ttf::adm-mono ttf::adm-fixed ttf::adm-prop;`
#
# Ref: https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md

# mono
[buildPlans.adm-mono]
family = "Adm Mono"
spacing = "normal"
serifs = "slab"
no-cv-ss = true
no-ligation = true

[buildPlans.adm-mono.variants.design]
capital-a = "straight-top-serifed"
capital-b = "more-asymmetric-bilateral-serifed"
capital-c = "unilateral-inward-serifed"
capital-d = "more-rounded-bilateral-serifed"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothless-corner-inward-serifed-capped"
capital-h = "top-left-serifed"
capital-i = "serifed"
capital-j = "serifed-both-sides"
capital-k = "curly-top-left-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "motion-serifed"
capital-p = "closed"
capital-r = "curly-motion-serifed"
capital-s = "bilateral-inward-serifed"
capital-t = "serifed"
capital-u = "toothless-rounded-unilateral-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "straight-top-serifed"
a = "double-storey-tailed"
b = "toothed-motion-serifed"
c = "unilateral-inward-serifed"
d = "tailed-serifed"
f = "serifed-crossbar-at-x-height"
g = "double-storey"
h = "straight-top-left-serifed"
k = "curly-top-left-serifed"
m = "top-left-serifed"
n = "straight-top-left-serifed"
s = "serifless"
t = "standard-short-neck2"
u = "tailed-motion-serifed"
v = "straight-motion-serifed"
w = "straight-flat-top-motion-serifed"
x = "straight-motion-serifed"
y = "straight-turn-motion-serifed"
z = "straight-top-serifed"
capital-gamma = "top-right-serifed"
cyrl-capital-ka = "curly-top-left-serifed"
cyrl-ka = "curly-top-left-serifed"
cyrl-ef = "top-serifed"
cyrl-capital-ya = "curly"
zero = "slashed-oval"
one = "no-base-long-top-serif"
two = "straight-neck"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "open-contour"
seven = "bend-serifed"
eight = "two-circles"
nine = "open-contour"
asterisk = "turn-hex-low"
number-sign = "slanted"
ampersand = "upper-open"
percent = "rings-continuous-slash"

[buildPlans.adm-mono.variants.italic]
capital-h = "top-left-bottom-right-serifed"
capital-k = "curly-top-left-and-bottom-right-serifed"
a = "single-storey-tailed"
f = "tailed-crossbar-at-x-height"
g = "single-storey-serifed"
h = "tailed"
k = "diagonal-tailed-cursive-top-left-serifed"
l = "tailed-serifed"
m = "tailed-top-left-serifed"
n = "tailed-motion-serifed"
p = "eared"
q = "diagonal-tailed"
s = "bilateral-inward-serifed"
v = "cursive-serifed"
w = "cursive-motion-serifed"
x = "cursive"
y = "cursive-motion-serifed"
z = "cursive"
two = "curly-neck"
three = "flat-top"
four = "open"
eight = "crossing"

[buildPlans.adm-mono.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.adm-mono.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.adm-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.adm-mono.slopes.italic]
angle = 12
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.adm-mono.widths.normal]
shape = 620
menu = 5
css = "normal"

[buildPlans.adm-mono.metric-override]
sb = 80
cap = 700
xheight = 500

# Fixed
[buildPlans.adm-fixed]
family = "Adm Fixed"
spacing = "fixed"
serifs = "slab"
no-cv-ss = true
no-ligation = true

[buildPlans.adm-fixed.variants.design]
capital-a = "straight-top-serifed"
capital-b = "more-asymmetric-bilateral-serifed"
capital-c = "unilateral-inward-serifed"
capital-d = "more-rounded-bilateral-serifed"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothless-corner-inward-serifed-capped"
capital-h = "top-left-serifed"
capital-i = "serifed"
capital-j = "serifed-both-sides"
capital-k = "curly-top-left-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "motion-serifed"
capital-p = "closed"
capital-r = "curly-motion-serifed"
capital-s = "bilateral-inward-serifed"
capital-t = "serifed"
capital-u = "toothless-rounded-unilateral-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "straight-top-serifed"
a = "double-storey-tailed"
b = "toothed-motion-serifed"
c = "unilateral-inward-serifed"
d = "tailed-serifed"
f = "serifed-crossbar-at-x-height"
g = "double-storey"
h = "straight-top-left-serifed"
k = "curly-top-left-serifed"
m = "top-left-serifed"
n = "straight-top-left-serifed"
s = "serifless"
t = "standard-short-neck2"
u = "tailed-motion-serifed"
v = "straight-motion-serifed"
w = "straight-flat-top-motion-serifed"
x = "straight-motion-serifed"
y = "straight-turn-motion-serifed"
z = "straight-top-serifed"
capital-gamma = "top-right-serifed"
cyrl-capital-ka = "curly-top-left-serifed"
cyrl-ka = "curly-top-left-serifed"
cyrl-ef = "top-serifed"
cyrl-capital-ya = "curly"
zero = "slashed-oval"
one = "no-base-long-top-serif"
two = "straight-neck"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "open-contour"
seven = "bend-serifed"
eight = "two-circles"
nine = "open-contour"
asterisk = "turn-hex-low"
number-sign = "slanted"
ampersand = "upper-open"
percent = "rings-continuous-slash"

[buildPlans.adm-fixed.variants.italic]
capital-h = "top-left-bottom-right-serifed"
capital-k = "curly-top-left-and-bottom-right-serifed"
a = "single-storey-tailed"
f = "tailed-crossbar-at-x-height"
g = "single-storey-serifed"
h = "tailed"
k = "diagonal-tailed-cursive-top-left-serifed"
l = "tailed-serifed"
m = "tailed-top-left-serifed"
n = "tailed-motion-serifed"
p = "eared"
q = "diagonal-tailed"
s = "bilateral-inward-serifed"
v = "cursive-serifed"
w = "cursive-motion-serifed"
x = "cursive"
y = "cursive-motion-serifed"
z = "cursive"
two = "curly-neck"
three = "flat-top"
four = "open"
eight = "crossing"

[buildPlans.adm-fixed.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.adm-fixed.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.adm-fixed.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.adm-fixed.slopes.italic]
angle = 12
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.adm-fixed.widths.normal]
shape = 620
menu = 5
css = "normal"

[buildPlans.adm-fixed.metric-override]
sb = 80
cap = 700
xheight = 500

# quasi-proportional
[buildPlans.adm-prop]
family = "Adm Prop"
spacing = "quasi-proportional"
serifs = "slab"
no-cv-ss = true
no-ligation = true

[buildPlans.adm-prop.variants.design]
capital-a = "straight-top-serifed"
capital-b = "more-asymmetric-bilateral-serifed"
capital-c = "unilateral-inward-serifed"
capital-d = "more-rounded-bilateral-serifed"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothless-corner-inward-serifed-capped"
capital-h = "top-left-serifed"
capital-i = "serifed"
capital-j = "serifed-both-sides"
capital-k = "curly-top-left-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "motion-serifed"
capital-p = "closed"
capital-r = "curly-motion-serifed"
capital-s = "bilateral-inward-serifed"
capital-t = "serifed"
capital-u = "toothless-rounded-unilateral-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "straight-top-serifed"
a = "double-storey-tailed"
b = "toothed-motion-serifed"
c = "unilateral-inward-serifed"
d = "tailed-serifed"
f = "serifed-crossbar-at-x-height"
g = "double-storey"
h = "straight-top-left-serifed"
k = "curly-top-left-serifed"
m = "top-left-serifed"
n = "straight-top-left-serifed"
s = "serifless"
t = "standard-short-neck2"
u = "tailed-motion-serifed"
v = "straight-motion-serifed"
w = "straight-flat-top-motion-serifed"
x = "straight-motion-serifed"
y = "straight-turn-motion-serifed"
z = "straight-top-serifed"
capital-gamma = "top-right-serifed"
cyrl-capital-ka = "curly-top-left-serifed"
cyrl-ka = "curly-top-left-serifed"
cyrl-ef = "top-serifed"
cyrl-capital-ya = "curly"
zero = "slashed-oval"
one = "no-base-long-top-serif"
two = "straight-neck"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "open-contour"
seven = "bend-serifed"
eight = "two-circles"
nine = "open-contour"
asterisk = "turn-hex-low"
number-sign = "slanted"
ampersand = "upper-open"
percent = "rings-continuous-slash"

[buildPlans.adm-prop.variants.italic]
capital-h = "top-left-bottom-right-serifed"
capital-k = "curly-top-left-and-bottom-right-serifed"
a = "single-storey-tailed"
f = "tailed-crossbar-at-x-height"
g = "single-storey-serifed"
h = "tailed"
k = "diagonal-tailed-cursive-top-left-serifed"
l = "tailed-serifed"
m = "tailed-top-left-serifed"
n = "tailed-motion-serifed"
p = "eared"
q = "diagonal-tailed"
s = "bilateral-inward-serifed"
v = "cursive-serifed"
w = "cursive-motion-serifed"
x = "cursive"
y = "cursive-motion-serifed"
z = "cursive"
two = "curly-neck"
three = "flat-top"
four = "open"
eight = "crossing"

[buildPlans.adm-prop.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.adm-prop.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.adm-prop.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.adm-prop.slopes.italic]
angle = 12
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.adm-prop.widths.normal]
shape = 620
menu = 5
css = "normal"

[buildPlans.adm-prop.metric-override]
sb = 80
cap = 700
xheight = 500