# Custom build of Iosevka font.
# https://github.com/be5invis/Iosevka
#
# Three variants:
#   Mono (for coding)
#   Fixed (for terminal)
#   Prop (quasi-proportional, for comment and docs)
#
# Properties:
#   Type: Serif-slab
#   4 styles: regular, italic, bold, bold-italic
#   width: normal as extended
#   No ligations
#
# How to make a custom build:
#   1. Create a custom build configuration using https://typeof.net/Iosevka/customizer
#   2. Save your configuration as private-build-plans.toml (Add more as needed)
#   3. Go to the directory where private-build-plans.toml is located
#   4. Run `docker run -it -v $(pwd):/build avivace/iosevka-build -- ttf::adm-sans-mono ttf::adm-sans-fixed ttf::adm-sans-prop`
#
# Build from source repo
#   1. Create a custom build configuration using https://typeof.net/Iosevka/customizer
#   2. Save your configuration as private-build-plans.toml (Add more as needed)
#   3. Put private-build-plans.toml under the root directory of the repo
#   4. Install nodejs and ttfautohint
#   5. Go to the root directory of the repo
#   6. Run `npm install; npm run build -- ttf::adm-sans-mono ttf::adm-sans-fixed ttf::adm-sans-prop;`
#
# Ref: https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md

# mono
[buildPlans.adm-sans-mono]
family = "Adm Sans Mono"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
no-ligation = true

[buildPlans.adm-sans-mono.variants.design]
capital-d = "more-rounded-serifless"
capital-j = "serifed-both-sides"
capital-k = "symmetric-connected-serifless"
capital-m = "slanted-sides-hanging"
capital-q = "crossing"
capital-r = "curly"
capital-s = "bilateral-inward-serifed"
capital-w = "straight-flat-top"
b = "toothless-corner"
f = "flat-hook-crossbar-at-x-height"
g = "double-storey"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "serifed-flat-tailed"
p = "earless-corner"
q = "earless-corner"
t = "flat-hook-short-neck2"
w = "straight-flat-top"
zero = "slashed-oval"
two = "straight-neck"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "bend-serifless"
eight = "crossing-asymmetric"
nine = "open-contour"
asterisk = "turn-hex-low"
number-sign = "slanted"
percent = "rings-continuous-slash"

[buildPlans.adm-sans-mono.variants.italic]
f = "flat-hook-tailed-crossbar-at-x-height"
g = "single-storey-earless-corner-flat-hook"
y = "cursive-flat-hook"

[buildPlans.adm-sans-mono.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.adm-sans-mono.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.adm-sans-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.adm-sans-mono.slopes.italic]
angle = 12
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.adm-sans-mono.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.adm-sans-mono.metric-override]
cap = 696
xheight = 515
parenSize = 926
symbolMid=322
leading=1228
archDepth=245
smallArchDepth=250


# Fixed
[buildPlans.adm-sans-fixed]
family = "Adm Sans Fixed"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true
no-ligation = true

[buildPlans.adm-sans-fixed.variants.design]
capital-d = "more-rounded-serifless"
capital-j = "serifed-both-sides"
capital-k = "symmetric-connected-serifless"
capital-m = "slanted-sides-hanging"
capital-q = "crossing"
capital-r = "curly"
capital-s = "bilateral-inward-serifed"
capital-w = "straight-flat-top"
b = "toothless-corner"
f = "flat-hook-crossbar-at-x-height"
g = "double-storey"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "serifed-flat-tailed"
p = "earless-corner"
q = "earless-corner"
t = "flat-hook-short-neck2"
w = "straight-flat-top"
zero = "slashed-oval"
two = "straight-neck"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "bend-serifless"
eight = "crossing-asymmetric"
nine = "open-contour"
asterisk = "turn-hex-low"
number-sign = "slanted"
percent = "rings-continuous-slash"

[buildPlans.adm-sans-fixed.variants.italic]
f = "flat-hook-tailed-crossbar-at-x-height"
g = "single-storey-earless-corner-flat-hook"
y = "cursive-flat-hook"

[buildPlans.adm-sans-fixed.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.adm-sans-fixed.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.adm-sans-fixed.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.adm-sans-fixed.slopes.italic]
angle = 12
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.adm-sans-fixed.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.adm-sans-fixed.metric-override]
cap = 696
xheight = 515
parenSize = 926
symbolMid=322
leading=1228
archDepth=245
smallArchDepth=250


# quasi-proportional
[buildPlans.adm-sans-prop]
family = "Adm Sans Prop"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true
no-ligation = true

[buildPlans.adm-sans-prop.variants.design]
capital-d = "more-rounded-serifless"
capital-j = "serifed-both-sides"
capital-k = "symmetric-connected-serifless"
capital-m = "slanted-sides-hanging"
capital-q = "crossing"
capital-r = "curly"
capital-s = "bilateral-inward-serifed"
capital-w = "straight-flat-top"
b = "toothless-corner"
f = "flat-hook-crossbar-at-x-height"
g = "double-storey"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "serifed-flat-tailed"
p = "earless-corner"
q = "earless-corner"
t = "flat-hook-short-neck2"
w = "straight-flat-top"
zero = "slashed-oval"
two = "straight-neck"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "bend-serifless"
eight = "crossing-asymmetric"
nine = "open-contour"
asterisk = "turn-hex-low"
number-sign = "slanted"
percent = "rings-continuous-slash"

[buildPlans.adm-sans-prop.variants.italic]
f = "flat-hook-tailed-crossbar-at-x-height"
g = "single-storey-earless-corner-flat-hook"
y = "cursive-flat-hook"

[buildPlans.adm-sans-prop.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.adm-sans-prop.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.adm-sans-prop.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.adm-sans-prop.slopes.italic]
angle = 12
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.adm-sans-prop.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.adm-sans-prop.metric-override]
cap = 696
xheight = 515
parenSize = 926
symbolMid=322
leading=1228
archDepth=245
smallArchDepth=250
