# Custom build of Iosevka font.
# https://github.com/be5invis/Iosevka
#
# Three variants:
#   Mono (for coding)
#   Fixed (for terminal)
#   Prop (quasi-proportional, for comment and docs)
#
# Properties:
#   Type: Serif-slab
#   4 styles: regular, italic, bold, bold-italic
#   2 widths: normal, extended
#   No ligations
#
# How to make a custom build:
#   1. Create a custom build configuration using https://typeof.net/Iosevka/customizer
#   2. Save your configuration as private-build-plans.toml (Add more as needed)
#   3. Run `docker run -it -v $(pwd):/build avivace/iosevka-build` where private-build-plans.toml is saved
#
# Ref: https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md

[buildPlans.admacro-mono]
family = "Admacro Mono"
spacing = "normal"
serifs = "slab"
no-cv-ss = true
no-ligation = true

[buildPlans.admacro-mono.variants.design]
capital-g = "toothless-corner-serifed-capped"
capital-j = "serifed-both-sides"
capital-k = "curly-serifed"
capital-m = "hanging"
capital-r = "curly"
capital-x = "straight-serifed"
f = "flat-hook-serifed"
k = "curly-serifed"
r = "corner-hooked-serifed"
t = "flat-hook-short-neck"
x = "curly-serifed"
w = "straight-flat-top"
y = "straight-turn"
zero = "slashed-oval"
two = "curly-neck"
four = "closed"
five = "oblique-upper-left-bar"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
asterisk = "penta-low"
paren = "normal"
brace = "curly"
number-sign = "slanted"
ampersand = "upper-open"
at = "short"
dollar = "through"
percent = "rings-continuous-slash"
ascii-single-quote = "straight"
question = "smooth"

[buildPlans.admacro-mono.variants.italic]
a = "single-storey-serifed"
b = "toothed-motion-serifed"
c = "unilateral-serifed"
d = "toothed-serifed"
f = "flat-hook-tailed"
g = "single-storey-serifless"
h = "straight"
j = "serifed"
k = "curly-serifed"
s = "bilateral-serifed"
t = "standard-short-neck"
u = "motion-serifed"
v = "cursive-serifed"
x = "curly-serifed"
w = "cursive"
y = "straight-turn-motion-serifed"
z = "curly-serifed"
six = "open-contour"
nine = "open-contour"

[buildPlans.admacro-mono.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.admacro-mono.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.admacro-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.admacro-mono.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.admacro-fixed]
family = "Admacro Fixed"
spacing = "fixed"
serifs = "slab"
no-cv-ss = true
no-ligation = true

[buildPlans.admacro-fixed.variants.design]
capital-g = "toothless-corner-serifed-capped"
capital-j = "serifed-both-sides"
capital-k = "curly-serifed"
capital-m = "hanging"
capital-r = "curly"
capital-x = "straight-serifed"
f = "flat-hook-serifed"
k = "curly-serifed"
r = "corner-hooked-serifed"
t = "flat-hook-short-neck"
x = "curly-serifed"
w = "straight-flat-top"
y = "straight-turn"
zero = "slashed-oval"
two = "curly-neck"
four = "closed"
five = "oblique-upper-left-bar"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
asterisk = "penta-low"
paren = "normal"
brace = "curly"
number-sign = "slanted"
ampersand = "upper-open"
at = "short"
dollar = "through"
percent = "rings-continuous-slash"
ascii-single-quote = "straight"
question = "smooth"

[buildPlans.admacro-fixed.variants.italic]
a = "single-storey-serifed"
b = "toothed-motion-serifed"
c = "unilateral-serifed"
d = "toothed-serifed"
f = "flat-hook-tailed"
g = "single-storey-serifless"
h = "straight"
j = "serifed"
k = "curly-serifed"
s = "bilateral-serifed"
t = "standard-short-neck"
u = "motion-serifed"
v = "cursive-serifed"
x = "curly-serifed"
w = "cursive"
y = "straight-turn-motion-serifed"
z = "curly-serifed"
six = "open-contour"
nine = "open-contour"

[buildPlans.admacro-mono.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.admacro-mono.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.admacro-fixed.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.admacro-fixed.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.admacro-prop]
family = "Admacro Prop"
spacing = "quasi-proportional"
serifs = "slab"
no-cv-ss = true
no-ligation = true

[buildPlans.admacro-prop.variants.design]
capital-g = "toothless-corner-serifed-capped"
capital-j = "serifed-both-sides"
capital-k = "curly-serifed"
capital-m = "hanging"
capital-r = "curly"
capital-x = "straight-serifed"
f = "flat-hook-serifed"
k = "curly-serifed"
r = "corner-hooked-serifed"
t = "flat-hook-short-neck"
x = "curly-serifed"
w = "straight-flat-top"
y = "straight-turn"
zero = "slashed-oval"
two = "curly-neck"
four = "closed"
five = "oblique-upper-left-bar"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
asterisk = "penta-low"
paren = "normal"
brace = "curly"
# brace = "straight"
number-sign = "slanted"
ampersand = "upper-open"
at = "short"
dollar = "through"
percent = "rings-continuous-slash"
ascii-single-quote = "straight"
question = "smooth"

[buildPlans.admacro-mono.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.admacro-mono.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.admacro-prop.variants.italic]
a = "single-storey-serifed"
b = "toothed-motion-serifed"
c = "unilateral-serifed"
d = "toothed-serifed"
f = "flat-hook-tailed"
g = "single-storey-serifless"
h = "straight"
j = "serifed"
k = "curly-serifed"
s = "bilateral-serifed"
t = "standard-short-neck"
u = "motion-serifed"
v = "cursive-serifed"
x = "curly-serifed"
w = "cursive"
y = "straight-turn-motion-serifed"
z = "curly-serifed"
six = "open-contour"
nine = "open-contour"

[buildPlans.admacro-mono.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.admacro-mono.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.admacro-prop.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.admacro-prop.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
