(defalias 'sfa 'set-face-attribute)

(defun reset ()
  (sfa 'font-lock-function-name-face nil :foreground "black" :weight 'normal :slant 'normal)
  (sfa 'font-lock-variable-name-face nil :foreground "black" :weight 'normal :slant 'normal)
  (sfa 'default nil :foreground "black" :background "#F4EEE6" :weight 'normal :slant 'normal)
  (sfa 'font-lock-type-face nil :foreground "black":weight 'normal :slant 'normal)
  (sfa 'font-lock-keyword-face nil :foreground "black" :weight 'normal :slant 'normal)
  (sfa 'font-lock-constant-face nil :foreground "black" :weight 'normal :slant 'normal)
  (sfa 'font-lock-comment-face nil :foreground "black" :weight 'normal :slant 'normal)
  (sfa 'font-lock-builtin-face nil :foreground "black" :weight 'normal :slant 'normal)
  (sfa 'font-lock-string-face nil :foreground "black" :weight 'normal :slant 'normal)
  )

(defun solar-theme ()
  (sfa 'font-lock-function-name-face nil :foreground "#F8AB32")
  (sfa 'font-lock-variable-name-face nil :foreground "#EFE6E0")
  (sfa 'default nil :foreground "#EFE6E0" :background "#2D354B")
  (sfa 'font-lock-type-face nil :foreground "#EFE6E0")
  (sfa 'font-lock-keyword-face nil :foreground "#EFE6E0")
  (sfa 'font-lock-constant-face nil :foreground "#EFE6E0")
  (sfa 'font-lock-comment-face nil :foreground "#EFE6E0")
  (sfa 'font-lock-builtin-face nil :foreground "#EFE6E0")
  (sfa 'font-lock-string-face nil :foreground "#EFE6E0")
  )

(defun adm-light-theme ()
  "colour palette: https://flatuicolors.com/palette/gb"
  (sfa 'font-lock-function-name-face nil :foreground "#833471")
  (sfa 'font-lock-variable-name-face nil :foreground "#2c2c54")
  (sfa 'default nil :foreground "#2c2c54" :background "#ece4d0")
  (sfa 'font-lock-type-face nil :foreground "#833471")
  (sfa 'font-lock-keyword-face nil :foreground "#474787" :weight 'bold)
  (sfa 'font-lock-constant-face nil :foreground "#006266" :slant 'italic)
  (sfa 'font-lock-comment-face nil :foreground "#bf6139")
  (sfa 'font-lock-builtin-face nil :foreground "#474787" :weight 'bold)
  (sfa 'font-lock-string-face nil :foreground "#006266")
  )

;; (reset) 

;; (solar-theme)

;; (adm-light-theme)
