(load "~/prog/config/emacs/basic.el")
(load "~/prog/config/emacs/theme/theme.el")
(load "~/prog/config/emacs/font.el")
(load "~/prog/config/emacs/pkg/pkg.el")
(load "~/prog/config/emacs/org/org.el")
(load "~/prog/config/emacs/abbrevs.el")
(load "~/prog/config/emacs/misc.el")
