(defun warm-to-cool ()
  ;; Warm
  (set-face-attribute 'font-lock-constant-face nil :foreground "#731702")
  (set-face-attribute 'font-lock-variable-name-face nil :foreground "#BF5B21")
  (set-face-attribute 'font-lock-string-face nil :foreground "#F28705")
  (set-face-attribute 'font-lock-comment-face nil :foreground "#D9A404")

  ;; Neutral
  (set-face-attribute 'font-lock-function-name-face nil :foreground "#40241A")
  (set-face-attribute 'font-lock-type-face nil :foreground "#8C7C5E")
  (set-face-attribute 'default nil :foreground "#3E4A59")

  ;; Cool
  (set-face-attribute 'font-lock-keyword-face nil :foreground "slate gray")
  (set-face-attribute 'font-lock-builtin-face nil :foreground "dark slate gray")
  (set-face-attribute 'font-lock-builtin-face nil :foreground "red")
  )
(warm-to-cool)

(defun weighted-rainbow ()
  (set-face-attribute 'font-lock-function-name-face nil :foreground "purple4")
  (set-face-attribute 'font-lock-variable-name-face nil :foreground "red4")
  (set-face-attribute 'default nil :foreground "orange4")
  (set-face-attribute 'font-lock-type-face nil :foreground "brown4")
  (set-face-attribute 'font-lock-keyword-face nil :foreground "gold4")
  (set-face-attribute 'font-lock-constant-face nil :foreground "yellow4")
  (set-face-attribute 'font-lock-comment-face nil :foreground "green4")
  (set-face-attribute 'font-lock-builtin-face nil :foreground "cyan4")
  (set-face-attribute 'font-lock-string-face nil :foreground "blue4")
  )
(weighted-rainbow)

(defun reset ()
  (set-face-attribute 'font-lock-function-name-face nil :foreground "black")
  (set-face-attribute 'font-lock-variable-name-face nil :foreground "black")
  (set-face-attribute 'default nil :foreground "black")
  (set-face-attribute 'font-lock-type-face nil :foreground "black")
  (set-face-attribute 'font-lock-keyword-face nil :foreground "black")
  (set-face-attribute 'font-lock-constant-face nil :foreground "black")
  (set-face-attribute 'font-lock-comment-face nil :foreground "black")
  (set-face-attribute 'font-lock-builtin-face nil :foreground "black")
  (set-face-attribute 'font-lock-string-face nil :foreground "black")
  )

(defun colorful-1 ()
  (set-face-attribute 'font-lock-function-name-face nil :foreground "#9D3C3C")
  (set-face-attribute 'font-lock-variable-name-face nil :foreground "# #9D593C")
  (set-face-attribute 'default nil :foreground "#9E773C")
  (set-face-attribute 'font-lock-type-face nil :foreground "#9E943C")
  (set-face-attribute 'font-lock-keyword-face nil :foreground "#8A9E3C")
  (set-face-attribute 'font-lock-constant-face nil :foreground "#6D9E3C")
  (set-face-attribute 'font-lock-comment-face nil :foreground "#509E3C")
  (set-face-attribute 'font-lock-builtin-face nil :foreground "#3C9E46")
  (set-face-attribute 'font-lock-string-face nil :foreground "#3C9E63")
  )
(colorful-1)


(defun colorful-2 ()
  (set-face-attribute 'font-lock-function-name-face nil :foreground "#9E0000")
  (set-face-attribute 'font-lock-variable-name-face nil :foreground "#9E450B")
  (set-face-attribute 'default nil :foreground "#9E650F")
  (set-face-attribute 'font-lock-type-face nil :foreground "#9E9017")
  (set-face-attribute 'font-lock-keyword-face nil :foreground "#479E84")
  (set-face-attribute 'font-lock-constant-face nil :foreground "#3F9E65")
  (set-face-attribute 'font-lock-comment-face nil :foreground "#56889E")
  (set-face-attribute 'font-lock-builtin-face nil :foreground "#5E789E")
  (set-face-attribute 'font-lock-string-face nil :foreground "#676C9E")
  )
(colorful-2)


(defun colorful-aa ()
  (set-face-attribute 'font-lock-function-name-face nil :foreground "#EB0000")
  (set-face-attribute 'font-lock-variable-name-face nil :foreground "#BF540D")
  (set-face-attribute 'default nil :foreground "#A3680F")
  (set-face-attribute 'font-lock-type-face nil :foreground "#82771")
  (set-face-attribute 'font-lock-keyword-face nil :foreground "#3A826E")
  (set-face-attribute 'font-lock-constant-face nil :foreground "#348354")
  (set-face-attribute 'font-lock-comment-face nil :foreground "#4D7C8F")
  (set-face-attribute 'font-lock-builtin-face nil :foreground "#5E779C")
  (set-face-attribute 'font-lock-string-face nil :foreground "#7072A4")
  )
(colorful-aa)


(defun colorful-aaa ()
  (set-face-attribute 'font-lock-function-name-face nil :foreground "#A30000")
  (set-face-attribute 'font-lock-variable-name-face nil :foreground "#80390A")
  (set-face-attribute 'default nil :foreground "#684208")
  (set-face-attribute 'font-lock-type-face nil :foreground "#514A0B")
  (set-face-attribute 'font-lock-keyword-face nil :foreground "#245144")
  (set-face-attribute 'font-lock-constant-face nil :foreground "#22593A")
  (set-face-attribute 'font-lock-comment-face nil :foreground "#33535B")
  (set-face-attribute 'font-lock-builtin-face nil :foreground "#3D4A66")
  (set-face-attribute 'font-lock-string-face nil :foreground "#4A4A4A")
  )
(colorful-aaa)

(defun weighted-rainbow-aaa ()
  (set-face-attribute 'font-lock-function-name-face nil :foreground "#941508")
  (set-face-attribute 'font-lock-variable-name-face nil :foreground "#801300")
  (set-face-attribute 'default nil :foreground "#6D4000")
  (set-face-attribute 'font-lock-type-face nil :foreground "#604525")
  (set-face-attribute 'font-lock-keyword-face nil :foreground "#574A00")
  (set-face-attribute 'font-lock-constant-face nil :foreground "#4E4D00")
  (set-face-attribute 'font-lock-comment-face nil :foreground "#004B00")
  (set-face-attribute 'font-lock-builtin-face nil :foreground "#005354")
  (set-face-attribute 'font-lock-string-face nil :foreground "#042BDB")
  )
(weighted-rainbow-aaa)
(weighted-rainbow)


(defun sss ()
  (set-face-attribute 'font-lock-function-name-face nil :foreground "#B2171A")
  (set-face-attribute 'font-lock-variable-name-face nil :foreground "#8B4805")
  (set-face-attribute 'default nil :foreground "#6D5539")
  (set-face-attribute 'font-lock-type-face nil :foreground "#705604")
  (set-face-attribute 'font-lock-keyword-face nil :foreground "#15681A")
  (set-face-attribute 'font-lock-constant-face nil :foreground "#006465")
  (set-face-attribute 'font-lock-comment-face nil :foreground "#094ED1")
  (set-face-attribute 'font-lock-builtin-face nil :foreground "#862BB6")
  (set-face-attribute 'font-lock-string-face nil :foreground "#5A5A5A")
  )
(sss)


(defun sss ()
  (set-face-attribute 'font-lock-function-name-face nil :foreground "#B2171A")
  (set-face-attribute 'font-lock-variable-name-face nil :foreground "#8B4805")
  (set-face-attribute 'default nil :foreground "#6D5539")
  (set-face-attribute 'font-lock-type-face nil :foreground "#705604")
  (set-face-attribute 'font-lock-keyword-face nil :foreground "#15681A")
  (set-face-attribute 'font-lock-constant-face nil :foreground "#006465")
  (set-face-attribute 'font-lock-comment-face nil :foreground "#094ED1")
  (set-face-attribute 'font-lock-builtin-face nil :foreground "#862BB6")
  (set-face-attribute 'font-lock-string-face nil :foreground "#5A5A5A")
  )
(sss)


(defun sss-aaa ()
  (set-face-attribute 'font-lock-function-name-face nil :foreground "#7B2E30")
  (set-face-attribute 'font-lock-variable-name-face nil :foreground "#7C4004")
  (set-face-attribute 'default nil :foreground "#0000FF")
  (set-face-attribute 'default nil :foreground "midnight blue" :background "LightYellow1")
  (set-face-attribute 'font-lock-type-face nil :foreground "#644C04")
  (set-face-attribute 'font-lock-keyword-face nil :foreground "#135C17")
  (set-face-attribute 'font-lock-constant-face nil :foreground "#00595A")
  (set-face-attribute 'font-lock-comment-face nil :foreground "#0845BA")
  (set-face-attribute 'font-lock-builtin-face nil :foreground "#7726A2")
  (set-face-attribute 'font-lock-string-face nil :foreground "#4F4F4F")
  )
(sss-aaa)

(reset)
(warm-to-cool)
(weighted-rainbow)
